project_id = "nhhdxwgrmcdsapbuvelx"

[functions.onboarding-api]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.get-google-tokens]
verify_jwt = false

[functions.send-project-invite]
verify_jwt = true

[functions.accept-project-invite]
verify_jwt = true

[functions.list-user-invitations]
verify_jwt = true

[functions.decline-project-invite]
verify_jwt = true

[functions.get-invite-details]
verify_jwt = false
